version: "3.8"

services:
  api:
    build: .
    image: agenda
    ports:
      - "8080:8080"
    environment:
      BD_URL: ${BD_URL}
      BD_USERNAME: ${BD_USERNAME}
      BD_PASSWORD: ${BD_PASSWORD}
      MANAGEMENT_METRICS_ENABLE_PROCESS_CPU: "false"
    depends_on: []