services:
  api:
    build: .
    image: agenda
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14.13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agendamentos
    ports:
        - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:

